export const SEED_FLASHCARDS: Record<string, { front: string; back: string }[]> = {
  'Sequence Diagrams': [
    { front: 'What does a lifeline represent in a sequence diagram?', back: 'An object or participant that exists and can send/receive messages over time — drawn as a named box with a dashed vertical line.' },
    { front: 'What is an activation bar in a sequence diagram?', back: 'A thin rectangle on a lifeline showing when an object is active (executing a method). Also called an execution specification.' },
    { front: 'What is the difference between synchronous and asynchronous messages?', back: 'Synchronous (solid arrowhead): sender waits for a response. Asynchronous (open arrowhead): sender continues without waiting.' },
    { front: 'What does a "combined fragment" box with "alt" mean?', back: 'An alternative — like an if/else. Each guard condition is shown in square brackets; only one path executes per interaction.' },
    { front: 'What does "ref" mean in a sequence diagram?', back: 'A reference to another sequence diagram — used to avoid repetition and keep complex flows readable.' },
    { front: 'How is a return message shown?', back: 'As a dashed arrow pointing back to the caller, optionally labeled with the return value.' },
    { front: 'What is a "loop" combined fragment?', back: 'A fragment that repeats — labeled with the iteration condition, e.g., loop(1,5) repeats 1 to 5 times.' },
    { front: 'What is the "create" message stereotype used for?', back: 'To show instantiation — the arrowhead points to the lifeline head of the newly created object.' },
  ],

  'Control Systems (Hardware)': [
    { front: 'What is a sensor in a control system?', back: 'A device that measures a physical quantity (temperature, pressure, position) and converts it to an electrical signal for the controller.' },
    { front: 'What is an actuator?', back: 'A device that converts a control signal into physical action — examples: servo motor, hydraulic cylinder, pneumatic valve.' },
    { front: 'What is the plant in a control system?', back: 'The physical process or system being controlled (e.g., aircraft, furnace, robotic arm). The controller manipulates the plant via actuators.' },
    { front: 'What is a transducer?', back: 'A device that converts one form of energy to another. In control systems, typically converts physical quantities to electrical signals (or vice versa).' },
    { front: 'What is signal conditioning?', back: 'Amplification, filtering, or conversion of a raw sensor signal to make it usable by the controller (e.g., scaling 4-20 mA to 0-10 V).' },
    { front: 'What is a feedback loop?', back: 'A control architecture where the output is measured and fed back to the input, allowing the controller to compare the actual output to the desired setpoint and correct error.' },
    { front: 'What does LVDT stand for and what does it measure?', back: 'Linear Variable Differential Transformer. Measures linear displacement (position) with high accuracy, no contact wear.' },
    { front: 'What is encoder resolution?', back: 'The smallest position change the encoder can detect, typically in counts-per-revolution (CPR) or pulses-per-revolution (PPR).' },
  ],

  'Control Systems (Software)': [
    { front: 'What is a control loop scan rate?', back: 'How often the control loop executes (e.g., every 10 ms = 100 Hz). Faster rates improve responsiveness but increase CPU load.' },
    { front: 'What is a state machine in a control system?', back: 'A model where the system is always in one defined state, and transitions between states are triggered by events or conditions.' },
    { front: 'What is a watchdog timer?', back: 'A hardware or software timer that resets the system if the control software does not "kick" it within a set interval — detects software hangs.' },
    { front: 'What is determinism in real-time control software?', back: 'The guarantee that operations complete in a bounded, predictable time. Critical for safety-critical and hard real-time systems.' },
    { front: 'What is a setpoint?', back: 'The desired target value for a controlled variable (e.g., target speed = 1500 RPM, target temperature = 200°C).' },
    { front: 'What is process variable (PV)?', back: 'The actual measured value of the quantity being controlled — compared to the setpoint to compute the error signal.' },
    { front: 'What is anti-windup in a PID controller?', back: 'A technique to prevent the integrator from accumulating large errors when the actuator is saturated (at its limit), which would cause overshooting.' },
    { front: 'What is a deadband?', back: 'A range around the setpoint where no corrective action is taken — reduces unnecessary actuator wear from small oscillations.' },
  ],

  'PID Controls': [
    { front: 'What does PID stand for?', back: 'Proportional–Integral–Derivative. A feedback control algorithm that corrects error using three terms.' },
    { front: 'What does the Proportional term do?', back: 'Produces output proportional to current error: P = Kp × e(t). Reduces error but rarely eliminates it (leaves steady-state error).' },
    { front: 'What does the Integral term do?', back: 'Accumulates past error to eliminate steady-state offset: I = Ki × ∫e(t)dt. Can cause overshoot if too large.' },
    { front: 'What does the Derivative term do?', back: 'Responds to rate of error change to dampen overshoot: D = Kd × de(t)/dt. Sensitive to noise — often filtered.' },
    { front: 'What is Kp, Ki, Kd?', back: 'Tuning gains for Proportional, Integral, and Derivative terms respectively. Adjusting these balances response speed, overshoot, and stability.' },
    { front: 'What is steady-state error?', back: 'The remaining difference between setpoint and output after the system has stabilized. P-only controllers often have this; the I term eliminates it.' },
    { front: 'What is overshoot?', back: 'When the controlled variable exceeds the setpoint before settling. Caused by too-high Kp or Ki, or insufficient Kd.' },
    { front: 'What is the Ziegler-Nichols tuning method?', back: 'A heuristic method: increase Kp until sustained oscillation (Ku = ultimate gain, Pu = period), then set Kp=0.6Ku, Ki=2Kp/Pu, Kd=KpPu/8.' },
    { front: 'What is a cascade PID?', back: 'Two PID loops nested: an outer loop sets the setpoint for an inner loop. Common in position/velocity control (outer: position, inner: velocity).' },
  ],

  'Solenoid Valves': [
    { front: 'How does a solenoid valve work?', back: 'An electromagnetic coil creates a magnetic field when energized, pulling a plunger to open or close a valve seat and control fluid/gas flow.' },
    { front: 'What is a normally-open (NO) solenoid valve?', back: 'The valve is open when de-energized (no power). Energizing the coil closes it. Used where flow must continue during power loss.' },
    { front: 'What is a normally-closed (NC) solenoid valve?', back: 'The valve is closed when de-energized. Energizing opens it. Most common configuration — safe in power-off state.' },
    { front: 'What is a 2-way vs 3-way solenoid valve?', back: '2-way: controls one flow path (on/off). 3-way: has three ports — can divert flow between two paths or mix flows.' },
    { front: 'What is valve hysteresis?', back: 'The difference in pressure/current between when the valve opens vs. when it closes. Affects precision in proportional valve control.' },
    { front: 'What is a proportional solenoid valve?', back: 'A valve where flow is continuously variable in proportion to the control current, not just fully open/closed.' },
    { front: 'What does IP65 rating mean for a solenoid valve?', back: 'Ingress Protection: totally dust-tight and protected against low-pressure water jets. Important for outdoor/harsh-environment installations.' },
    { front: 'What causes solenoid valve coil failure?', back: 'Over-voltage, excessive duty cycle, high ambient temperature, or moisture ingress — these overheat the coil and burn out the winding.' },
  ],

  'Kubernetes': [
    { front: 'What is a Pod in Kubernetes?', back: 'The smallest deployable unit in K8s. A Pod wraps one or more containers that share network and storage, and run on the same node.' },
    { front: 'What is a Deployment?', back: 'A K8s object that declaratively manages a set of replica Pods, handling rolling updates, rollbacks, and scaling.' },
    { front: 'What is a Service in Kubernetes?', back: 'An abstraction that provides a stable IP/DNS name for a set of Pods, enabling load balancing and service discovery within the cluster.' },
    { front: 'What is a ConfigMap?', back: 'A K8s object that stores non-sensitive configuration data as key-value pairs, injected into Pods as env vars or mounted files.' },
    { front: 'What is the difference between ClusterIP, NodePort, and LoadBalancer?', back: 'ClusterIP: internal cluster only. NodePort: exposes via static port on each node. LoadBalancer: provisions external cloud load balancer.' },
    { front: 'What is a namespace in Kubernetes?', back: 'A virtual cluster within a cluster — used to isolate resources between teams, environments (dev/staging/prod), or applications.' },
    { front: 'What is a liveness probe vs readiness probe?', back: 'Liveness: restarts the container if it fails (detects deadlock). Readiness: removes Pod from Service load balancer if it fails (not ready to serve).' },
    { front: 'What is a DaemonSet?', back: 'A K8s object ensuring one Pod runs on every (or selected) node — used for log collectors, monitoring agents, or node-level services.' },
  ],

  'Control Modes & States': [
    { front: 'What is a safe state in a control system?', back: 'A known, stable configuration the system transitions to when a fault is detected — typically deenergizes actuators and holds last safe position.' },
    { front: 'What is the difference between AUTO and MANUAL mode?', back: 'AUTO: the controller computes output from sensor feedback. MANUAL: the operator directly sets the output, bypassing the control algorithm.' },
    { front: 'What is a mode transition?', back: 'A controlled change between defined operational states (e.g., INIT → STANDBY → OPERATE → FAULT) triggered by events or commands.' },
    { front: 'What is an interlock?', back: 'A condition that must be met before a mode transition or action is allowed. Prevents unsafe operation (e.g., hydraulic pressure must be above X before extending actuator).' },
    { front: 'What is inhibit in control systems?', back: 'A flag or signal that prevents a command or function from executing — used for safety, maintenance lockout, or sequencing.' },
    { front: 'What is BITE mode?', back: 'Built-In Test Equipment mode — the system runs self-diagnostics to verify hardware and software health before or during operation.' },
    { front: 'What is a hold state?', back: 'A state where the system maintains its current output and does not respond to new commands — used during fault investigation or while awaiting clearance.' },
    { front: 'What is a latched fault?', back: 'A fault condition that persists even after the root cause is cleared, requiring an explicit operator reset to clear it.' },
  ],

  'Altitude Control Systems': [
    { front: 'What sensor is commonly used to measure altitude?', back: 'A barometric pressure sensor (altimeter). Absolute altitude uses static pressure vs. standard atmosphere; radar altimeters use radio waves for ground clearance.' },
    { front: 'What is pressure altitude?', back: 'Altitude calculated from atmospheric pressure relative to the standard datum plane (29.92 inHg / 1013.25 hPa at sea level).' },
    { front: 'What is a baro-inertial altitude system?', back: 'A system that blends barometric altitude (accurate at steady state) with inertial navigation (accurate short-term) using a Kalman filter.' },
    { front: 'What is altitude hold autopilot mode?', back: 'The aircraft\'s autopilot maintains a commanded altitude by adjusting pitch (via elevator) to counteract vertical speed deviations.' },
    { front: 'What is RVSM?', back: 'Reduced Vertical Separation Minimum — 1,000 ft separation between FL290 and FL410, requiring precision altimetry (±75 ft) and autopilot.' },
    { front: 'What is a vertical speed indicator (VSI)?', back: 'An instrument that shows rate of climb or descent (ft/min or m/s) — helps pilots control altitude transitions smoothly.' },
    { front: 'What causes altitude control lag in large aircraft?', back: 'Aircraft inertia (mass × velocity), actuator response time, and slow aerodynamic response to elevator inputs.' },
  ],

  'Sheaves & Load Pins': [
    { front: 'What is a sheave?', back: 'A grooved wheel or pulley used with rope or cable to change direction of a load or gain mechanical advantage in a rigging system.' },
    { front: 'What is mechanical advantage in a block-and-tackle system?', back: 'The ratio of load to effort force. With n rope segments supporting the load, MA = n (ignoring friction).' },
    { front: 'What is a load pin?', back: 'A specially designed pin with embedded strain gauges that replaces a standard shackle pin to measure shear force (and thus load) in a rigging point.' },
    { front: 'What is wire rope fatigue and how does sheave D/d ratio affect it?', back: 'Wire rope fatigues when bent over sheaves. Higher D/d ratio (sheave diameter to rope diameter) reduces bending stress and extends rope life. Minimum D/d is typically 20:1 to 40:1.' },
    { front: 'How does a load cell differ from a load pin?', back: 'A load cell measures compressive/tensile force in-line (e.g., a beam under a platform). A load pin is installed in a clevis or block pivot and measures shear force.' },
    { front: 'What is fleet angle in sheave systems?', back: 'The angle between the rope and the groove centerline as it wraps the sheave. Excessive fleet angle (>2-4°) causes rope wear and vibration.' },
    { front: 'What is a snatch block?', back: 'A single-sheave block that opens on the side to accept a rope without reeving — allows quick rigging changes in the field.' },
  ],

  'LVDT & LVIT': [
    { front: 'What does LVDT stand for?', back: 'Linear Variable Differential Transformer — a contactless inductive sensor that measures linear displacement with high accuracy and infinite resolution.' },
    { front: 'How does an LVDT work?', back: 'A moveable iron core slides within a primary coil and two secondary coils. Displacement changes the differential voltage between secondaries, proportional to position.' },
    { front: 'What is LVIT?', back: 'Linear Variable Inductance Transducer — similar to LVDT but uses inductance change rather than differential transformer voltage. Simpler, often used in hydraulic cylinders.' },
    { front: 'What are the advantages of LVDT over a potentiometer?', back: 'No contact wear, infinite resolution, excellent repeatability, operates in harsh environments, and output is immune to electrical noise from sliding contacts.' },
    { front: 'What is the null position of an LVDT?', back: 'The center position where the core is symmetrically placed between the two secondaries — output voltage is zero (or minimum with AC excitation).' },
    { front: 'What excitation frequency is typical for an LVDT?', back: 'Usually 1–10 kHz AC for laboratory/industrial types, though some use DC-LVDT signal conditioners that supply and demodulate internally.' },
    { front: 'What is LVDT stroke?', back: 'The full measuring range — the total linear travel over which the output is linear and accurate (e.g., ±25 mm, ±100 mm).' },
  ],

  'Actuator Control': [
    { front: 'What are the three main types of actuators?', back: 'Electric (servo/stepper), hydraulic (cylinder/motor), and pneumatic (cylinder/rotary). Each trades off force, speed, precision, and environment suitability.' },
    { front: 'What is a servo actuator?', back: 'A closed-loop actuator with feedback (typically encoder or resolver) that controls position, velocity, or torque precisely via a servo drive.' },
    { front: 'What is a hydraulic servo valve?', back: 'An electrohydraulic valve that converts a small electrical signal into proportional hydraulic flow — used for precise position/force control in hydraulic actuators.' },
    { front: 'What is actuator stiction?', back: 'Static friction that causes the actuator to stick at rest and produce jerky motion at low speeds. Degrades precision and causes limit cycles in tight control loops.' },
    { front: 'What is backlash in a mechanical actuator?', back: 'Dead zone in a gear/leadscrew where no output motion occurs as the input reverses direction. Causes positioning error and must be compensated in control software.' },
    { front: 'What is force fighting in redundant actuators?', back: 'When two actuators driving the same load receive slightly different commands, they fight each other — one pushes while the other resists. Mitigated by force equalization.' },
    { front: 'What is a linear actuator stroke end limit?', back: 'Mechanical or electrical stops that define the actuator\'s travel limits. Hardware limits prevent mechanical damage; software limits provide an earlier safety boundary.' },
  ],

  'Latches & Hatches': [
    { front: 'What is a hook-and-pin latch?', back: 'A latch where a rotating hook captures a fixed pin. Used in aircraft doors, panels, and access hatches. Simple, light, and reliable.' },
    { front: 'What is a rotary latch?', back: 'A latch that uses a rotating catch (ratchet-style) to engage a striker bolt. Used in automotive and aerospace doors for smooth, one-hand operation.' },
    { front: 'What is a flush-pull handle?', back: 'A recessed handle that lies flat with the surface when closed, reducing aero drag and snag hazards. Deployed by pulling the recess.' },
    { front: 'What is an electromechanical latch?', back: 'A latch incorporating a solenoid or motor for remote release. Can be commanded open/closed by a control system, used in automated doors and access panels.' },
    { front: 'What is latch verification sensing?', back: 'Microswitches or proximity sensors on the latch mechanism that confirm engaged/disengaged state — feed position data to the control system for safety interlocks.' },
    { front: 'What is a hatch open/close sequence?', back: 'A defined sequence ensuring safe operation: verify pressure equalization, unlock actuated seals, confirm clearances, then drive the hatch open. Reversed for closing.' },
    { front: 'What is a double-locking mechanism?', back: 'Two independent locking elements that must both be released to open — provides redundancy against inadvertent opening in safety-critical applications.' },
  ],

  'Joystick Control Algorithms': [
    { front: 'What is a joystick deadband?', back: 'A small zone around the center position where no output is generated — filters out hand tremor and sensor noise that would cause unintended motion.' },
    { front: 'What is joystick scaling (curve shaping)?', back: 'Mapping raw joystick input to output command using a non-linear curve — e.g., fine control near center, full rate at extremes. Improves precision for fine maneuvers.' },
    { front: 'What is rate mode vs position mode joystick control?', back: 'Rate mode: joystick deflection commands a velocity (e.g., crane moves at 2 m/s). Position mode: deflection maps directly to a target position.' },
    { front: 'What is joystick input filtering?', back: 'Low-pass filtering raw ADC readings to remove high-frequency noise — typically a moving average or IIR filter with a cutoff of 10-50 Hz.' },
    { front: 'What is cross-coupling in joystick control?', back: 'When motion on one axis (e.g., X) creates unintended motion on another axis (Y) — must be mechanically minimized and/or compensated in software.' },
    { front: 'What is a joystick authority limit?', back: 'A software cap on the maximum commanded rate or force — prevents the operator from commanding motion faster than the system can safely execute.' },
    { front: 'What is soft stop in joystick control?', back: 'A velocity-based limit that slows the commanded rate as the load approaches a position limit, ensuring a smooth stop rather than a hard impact.' },
    { front: 'What is joystick spring centering and how does software handle it?', back: 'The spring returns the joystick to center on release. Software detects near-zero deflection and commands hold or gradual decel depending on mode.' },
  ],

  'Hardware Automation': [
    { front: 'What is a PLC?', back: 'Programmable Logic Controller — an industrial computer that executes scan-cycle logic (ladder logic, structured text, etc.) to control machinery and processes.' },
    { front: 'What is a scan cycle in a PLC?', back: 'The repeating loop: read inputs → execute program → write outputs. Typical scan times are 1–100 ms.' },
    { front: 'What is ladder logic?', back: 'A PLC programming language that looks like relay-contact diagrams. Each rung checks contact conditions and, if true, activates a coil (output).' },
    { front: 'What is an RTU?', back: 'Remote Terminal Unit — collects field data (sensor readings, switch states) and transmits it to a control center, often over serial or Ethernet protocols.' },
    { front: 'What is SCADA?', back: 'Supervisory Control and Data Acquisition — a system for monitoring and controlling industrial processes using PLCs/RTUs and HMI software.' },
    { front: 'What is DIN rail?', back: 'A standardized metal rail (35 mm wide) used to mount control hardware like PLCs, terminal blocks, and relay modules in electrical panels.' },
    { front: 'What is a fieldbus?', back: 'An industrial communication protocol for real-time control of sensors and actuators — examples: PROFIBUS, DeviceNet, EtherCAT, Modbus RTU.' },
    { front: 'What is I/O mapping in a PLC system?', back: 'Assigning physical input/output terminals (wire connections) to software memory addresses (e.g., %I0.0 = proximity switch on terminal 1).' },
  ],

  'Circuit Card Assemblies (CCA)': [
    { front: 'What is a CCA?', back: 'Circuit Card Assembly — a printed circuit board (PCB) with all components soldered and tested, ready for installation in equipment.' },
    { front: 'What is a conformal coating?', back: 'A thin protective film (acrylic, epoxy, silicone, or polyurethane) applied to a CCA to resist moisture, dust, and corrosion in harsh environments.' },
    { front: 'What is a decoupling capacitor?', back: 'A capacitor placed close to an IC power pin to filter supply voltage noise and provide instantaneous current during switching transients.' },
    { front: 'What is EMI and how is it mitigated on a CCA?', back: 'Electromagnetic Interference — unwanted noise that disrupts circuits. Mitigated by ground planes, shielding, filtering, controlled impedance traces, and ferrite beads.' },
    { front: 'What is a ground plane?', back: 'A solid copper layer in a PCB dedicated to ground, reducing loop area, providing a return path for signals, and shielding against EMI.' },
    { front: 'What is impedance-controlled routing?', back: 'Designing trace width/spacing on high-speed signals to achieve a target characteristic impedance (typically 50Ω single-ended, 100Ω differential) and prevent reflections.' },
    { front: 'What is BGA and why is it challenging to rework?', back: 'Ball Grid Array — IC package with solder balls on the bottom. Challenging to rework because joints are hidden under the device; requires X-ray inspection to verify.' },
    { front: 'What is a JTAG boundary scan?', back: 'A standardized serial test interface (IEEE 1149.1) that allows testing of PCB interconnections and programming of FPGAs/flash without physical probes.' },
  ],

  'Built-In Test (BIT)': [
    { front: 'What are the three types of BIT?', back: 'IBIT (Initiated BIT): manually started diagnostic. CBIT (Continuous BIT): runs in background during operation. PBIT (Power-on BIT): runs at startup.' },
    { front: 'What is a BIT false alarm?', back: 'A BIT indication of fault when no real fault exists. False alarms reduce operator trust in the BIT system — NFF (No Fault Found) rate is a key metric.' },
    { front: 'What is fault isolation in BIT?', back: 'The ability of BIT to identify which specific LRU (Line Replaceable Unit) or component has failed, down to an ambiguity group.' },
    { front: 'What is an LRU?', back: 'Line Replaceable Unit — a module designed to be removed and replaced in the field without specialized tools or depot-level maintenance.' },
    { front: 'What is BIT coverage?', back: 'The percentage of detectable fault modes that BIT can detect. Typically expressed as Fault Detection Rate (FDR) and Fault Isolation Rate (FIR).' },
    { front: 'What is a built-in self-test (BIST) in digital hardware?', back: 'Logic embedded in an IC or FPGA that generates test patterns and evaluates responses — often using LFSR-based test patterns.' },
    { front: 'What is a BIT inhibit?', back: 'A mechanism to suppress BIT from triggering during certain operational phases (e.g., during launch, landing, or precision maneuvers) to avoid false interrupts.' },
  ],

  'Health & Status Monitoring': [
    { front: 'What is HUMS?', back: 'Health and Usage Monitoring System — continuously collects and analyzes sensor data to detect wear, predict failures, and optimize maintenance schedules.' },
    { front: 'What is a health status word?', back: 'A packed binary or enumeration field in a data packet indicating the operational health of a subsystem (e.g., OK=0, DEGRADED=1, FAILED=2).' },
    { front: 'What is a heartbeat signal?', back: 'A periodic message or pulse sent by a subsystem to indicate it is alive. Loss of heartbeat triggers a watchdog timeout and fault flag.' },
    { front: 'What is a FMEA?', back: 'Failure Mode and Effects Analysis — a systematic method to identify failure modes, their causes, effects on the system, and severity. Drives BIT requirements.' },
    { front: 'What is prognostics vs diagnostics?', back: 'Diagnostics: detecting and isolating a current fault. Prognostics: predicting remaining useful life before a fault occurs based on trends and models.' },
    { front: 'What is a BIT status register?', back: 'A memory-mapped register in embedded hardware where BIT results are stored as flags — polled by the main controller for health reporting.' },
    { front: 'What is threshold-based fault detection?', back: 'Comparing a measured value against a defined limit; if exceeded for a set duration, a fault is declared. Simple but requires careful limit-setting to avoid false alarms.' },
  ],

  'Hydraulic Valves': [
    { front: 'What is a directional control valve (DCV)?', back: 'A valve that controls the direction of hydraulic fluid flow to an actuator. Described by ports × positions, e.g., 4/3 (4 ports, 3 positions).' },
    { front: 'What is a pressure relief valve?', back: 'A normally-closed valve that opens when system pressure exceeds a set value, diverting flow to tank to protect the system from overpressure.' },
    { front: 'What is a check valve?', back: 'Allows fluid flow in one direction only — prevents backflow. Uses a ball, poppet, or flap seated by spring and pressure.' },
    { front: 'What is a proportional valve?', back: 'A valve where the spool position (and thus flow/pressure) is continuously variable in proportion to an electrical command signal — between on/off and servo valve.' },
    { front: 'What is a servo valve?', back: 'A high-precision electrohydraulic valve using a torque motor and nozzle-flapper or jet-pipe pilot stage for accurate, fast flow control in servo systems.' },
    { front: 'What is valve hysteresis and why does it matter?', back: 'The difference in output between increasing and decreasing command inputs. High hysteresis causes positioning error and limit cycling in closed-loop control.' },
    { front: 'What is a pilot-operated valve?', back: 'A large valve controlled by a small pilot valve — the pilot pressure shifts the main spool, allowing a small signal to control high-flow paths.' },
    { front: 'What is cavitation in a hydraulic valve?', back: 'Formation and collapse of vapor bubbles when fluid pressure drops below vapor pressure, causing noise, erosion, and damage to valve components.' },
  ],

  'gRPC': [
    { front: 'What is gRPC?', back: 'A high-performance RPC (Remote Procedure Call) framework by Google using HTTP/2 for transport and Protocol Buffers for serialization.' },
    { front: 'What is a .proto file?', back: 'The Interface Definition Language (IDL) file for gRPC — defines services, RPC methods, and message types that are compiled to language-specific stubs.' },
    { front: 'What are the four types of gRPC communication?', back: 'Unary (one request/one response), Server Streaming (one request/many responses), Client Streaming (many requests/one response), Bidirectional Streaming.' },
    { front: 'What are Protocol Buffers (protobuf)?', back: 'Binary serialization format used by gRPC — compact, fast, and schema-enforced. Much smaller and faster than JSON for the same data.' },
    { front: 'Why does gRPC use HTTP/2?', back: 'HTTP/2 enables multiplexed streams (multiple RPCs on one connection), header compression, server push, and binary framing — improving performance over HTTP/1.1.' },
    { front: 'What is a gRPC interceptor?', back: 'Middleware that wraps all RPC calls on client or server — used for logging, authentication, metrics, tracing, and retry logic.' },
    { front: 'What is gRPC status codes?', back: 'Standardized error codes (OK, CANCELLED, INVALID_ARGUMENT, NOT_FOUND, PERMISSION_DENIED, UNAVAILABLE, etc.) returned in the RPC response trailer.' },
    { front: 'What is gRPC-Gateway?', back: 'A protoc plugin that generates a reverse-proxy server to translate RESTful JSON APIs into gRPC calls — enables REST clients to talk to gRPC backends.' },
  ],

  'RabbitMQ': [
    { front: 'What is RabbitMQ?', back: 'An open-source message broker implementing AMQP, supporting message queuing, pub/sub, routing, and acknowledgment for asynchronous communication between services.' },
    { front: 'What is an exchange in RabbitMQ?', back: 'A routing component that receives messages from producers and routes them to queues based on routing rules. Types: Direct, Fanout, Topic, Headers.' },
    { front: 'What is a binding?', back: 'A link between an exchange and a queue, with an optional routing key or binding key that determines which messages are delivered to that queue.' },
    { front: 'What is message acknowledgment (ACK)?', back: 'A consumer sends an ACK after successfully processing a message, telling RabbitMQ it can be deleted from the queue. Without ACK, the message is requeued on consumer failure.' },
    { front: 'What is a dead letter exchange (DLX)?', back: 'An exchange where messages are routed when they are rejected, expired (TTL), or exceed queue length limits — used for error handling and retries.' },
    { front: 'What is a fanout exchange?', back: 'Routes messages to ALL bound queues, ignoring routing keys — used for broadcast/pub-sub where every subscriber gets every message.' },
    { front: 'What is a topic exchange?', back: 'Routes messages based on wildcard routing key patterns: * matches one word, # matches zero or more words. Enables flexible publish/subscribe routing.' },
    { front: 'What is RabbitMQ prefetch count?', back: 'The maximum number of unacknowledged messages a consumer can hold at once. Setting this to 1 ensures fair dispatch — each consumer gets one message at a time.' },
  ],
};
